In [110]:
import numpy as np
data = np.array ([12,34,46,57])
data

array([12, 34, 46, 57])

In [111]:
import numpy as np
d = np.array ([1,2,3,4])
d
d = d.astype(float)
d

array([1., 2., 3., 4.])

In [112]:
import numpy as np
data = np.array (([12,34,46,57]),dtype = (float))
data

array([12., 34., 46., 57.])

In [113]:
import numpy as np
data = np.array ([12,34,46,57])
data.shape

(4,)

In [114]:
import numpy as np
data = np.array ([12,34,46,57])
data.ndim

1

In [115]:
import numpy as np
data = np.array ([12,34,46,57])
data.size

4

In [116]:
import numpy as np
data = np.array ([12,34,46,57])
data[0]
data[2]

np.int64(46)

In [117]:
#2D &3D
import numpy as np
datas = np.array([[10,20,57,30,48],[22,75,19,90,80]])
datas

array([[10, 20, 57, 30, 48],
       [22, 75, 19, 90, 80]])

In [118]:
datas.dtype

dtype('int64')

In [119]:
#rows and co;umns
datas.shape

(2, 5)

In [120]:
datas.ndim

2

In [121]:
datas.size

10

In [122]:
datas[0]

array([10, 20, 57, 30, 48])

In [123]:
datas[0][1]

np.int64(20)

In [124]:
import numpy as np

dat =np.array ([[[12,34,56,77,59]]])
dat.shape

(1, 1, 5)

In [125]:
dat.dtype

dtype('int64')

In [126]:
dat.ndim

3

In [127]:
s = dat.astype(float)
s

array([[[12., 34., 56., 77., 59.]]])

In [128]:
#CFREATING BIGGER ARRAY
import numpy as np
da = np.array ([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]
     ],
     [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]
     ],
     [[31,32,33,34,35],[36,37,38,39,40],[41,42,43,44,45]
     ]    
])
da

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]]])

In [129]:
da[2,:,-3]

array([33, 38, 43])

In [130]:
da[1,:,-1]

array([20, 25, 30])

In [131]:
da.dtype

dtype('int64')

In [132]:
da.ndim

3

In [133]:
da.shape

(3, 3, 5)

In [134]:
da.size

45

In [135]:
da [0][2][3]

np.int64(14)

In [136]:

#ARRAY INTEX TASK WITH NUMPY
import numpy as np
a = np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [137]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
c = np.zeros((10))
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [139]:
d = np.ones((8))
d

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [140]:
e = np.random.random((6))
e

array([0.75553636, 0.64539552, 0.73596706, 0.38862305, 0.75597233,
       0.06805333])

In [141]:
f = np.identity(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [142]:
g = np.array([1,2,3,4,5])
g

array([1, 2, 3, 4, 5])

In [143]:
g[0]

np.int64(1)

In [144]:
g[2]

np.int64(3)

In [145]:
g[4]

np.int64(5)

In [146]:
h = np.array([[1,2,4,5,6],[7,8,9,10,11],[12,13,14,15,16]])
h

array([[ 1,  2,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [147]:
h[1][2]

np.int64(9)

In [148]:
h[0]

array([1, 2, 4, 5, 6])

In [149]:
h[2]

array([12, 13, 14, 15, 16])

In [150]:
print(h[:,-1])

[ 6 11 16]


#ARRAY RESHAPE

In [151]:
import numpy as np
sec= np.array([1,2,3,4,])
sec

array([1, 2, 3, 4])

In [152]:
print(sec.reshape(2,2))

[[1 2]
 [3 4]]


#random modules

In [153]:
print(np.random.rand(5))

[0.60770488 0.09633075 0.68425692 0.58607438 0.22992626]


In [154]:
print(np.random.randint(1,100,10))

[68 33 56 69 66 99 93 58 87 49]


In [155]:
print(np.random.randn(5))

[ 0.7724481   0.22512529 -1.64845665  1.61929605  0.74967724]


In [156]:
print(np.random.choice([10,20,30],5))

[20 10 10 20 10]


#iterating array

In [157]:
import numpy as np
ar= np.array([10,20,30])
ar

array([10, 20, 30])

In [158]:
for i in ar:
   print(i)

10
20
30


In [159]:
import numpy as np
arr= np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [160]:
for i in np.nditer(arr):
    print(i)

1
2
3
4


#joining array

In [161]:
import numpy as np
a= np.array([1,2])
b= np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


#stack,#vstack,#hstack

In [162]:
import numpy as np

a= np.array([1,2,3])
b= np.array([4,5,6])

In [163]:
print(np.stack((a,b)))

[[1 2 3]
 [4 5 6]]


In [164]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [165]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


#spliting array

In [166]:
import numpy as np
aa= np.array([1,2,3,4,5,6])
print(np.array_split(aa,2))

[array([1, 2, 3]), array([4, 5, 6])]


#searching array

In [167]:
print(np.where(aa==4))

(array([3]),)


In [168]:
print(np.where(aa>5))

(array([5]),)


#sorting array

In [169]:
print(np.sort(aa))

[1 2 3 4 5 6]


In [170]:
import numpy as np
aaa= np.array(["apple","orange","banana"])
print(np.sort(aaa))

['apple' 'banana' 'orange']


#filter array

In [171]:
import numpy as np
arra= np.array([1,2,3,4,5,6])
print(arra[arra%2==0])

[2 4 6]


#universel functions

In [172]:
import numpy as np
x= np.array([1,2,3])
y= np.array([10,20,30])

print(x + y)

[11 22 33]


In [173]:
print(x-y)

[ -9 -18 -27]


In [175]:
print(y * x)

[10 40 90]


In [180]:
print(x/2)

[0.5 1.  1.5]


In [179]:
print(x**2)

[1 4 9]


#universel functions

In [188]:
print(np.sqrt(y))
print(np.exp(y))
print(np.abs(y))
print(np.sin(y))
print(np.cos(y))
print(np.log(y))

[3.16227766 4.47213595 5.47722558]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]
[10 20 30]
[-0.54402111  0.91294525 -0.98803162]
[-0.83907153  0.40808206  0.15425145]
[2.30258509 2.99573227 3.40119738]


#agregation functions

In [189]:
import numpy as np
ay = np.array([2,4,6])
print(np.sum(ay))
print(np.median(ay))
print(np.mean(ay))
print(np.std(ay))
print(np.var(ay))
print(np.min(ay))
print(np.max(ay))
print(np.argmax(ay))
print(np.argmin(ay))

12
4.0
4.0
1.632993161855452
2.6666666666666665
2
6
2
0


#axis concept

In [195]:

import numpy as np
a =np.array([[1, 2, 3],
           [4, 5, 6]])
print(np.sum(a, axis=0)) 
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]
